---
- name: Determine if Atomic
  stat:
    path: /run/ostree-booted
  register: os_tree_check
  changed_when: false
  check_mode: no

- name: Set the is_atomic fact
  set_fact:
    is_atomic: true
  when: os_tree_check.stat.exists

- name: Get os_version from /etc/os-release
  raw: "grep '^VERSION_ID=' /etc/os-release | sed s'/VERSION_ID=//'"
  register: os_version
  check_mode: no

- name: Get distro name from /etc/os-release
  raw: "grep '^NAME=' /etc/os-release | sed s'/NAME=//'"
  register: distro
  check_mode: no

- name: Set the is_coreos fact
  set_fact:
    is_coreos: true
  when: "'CoreOS' in distro.stdout"

- name: Set the bin directory path for CoreOS
  set_fact:
    bin_dir: "/opt/bin"
  when: is_coreos

- name: Determine if has rpm
  stat:
    path: /usr/bin/rpm
  register: s
  changed_when: false
  check_mode: no

- name: Set the has_rpm fact
  set_fact:
    has_rpm: true
  when: s.stat.exists

# collect information about if firewalld package is installed
- include: rpm.yml
  when: has_rpm
